---
title: "Example Analytics"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---
# Overview

`r shiny::tags$h1("Overview", style="text-align:center")`

```{r setup, include=FALSE}
library(flexdashboard) 
library(tidyverse)

# Create dummy data for example
set.seed(345)
date_start <- as.Date("2018-01-01")
product_groups <- c("PG1", "PG2", "PG3")
products <- list(
  PG1 = c("A", "B", "C"),
  PG2 = c("D", "E", "F"),
  PG3 = c("G", "H")
)
data <- data.frame(
  product_group = sample(product_groups, 100, replace = T),
  trade_volume = rnorm(100, mean = 3448, sd = 200),
  date = date_start + 1:100
) %>% 
  group_by(id = row_number()) %>% 
  mutate(product = sample(unlist(products[[product_group]]), 1, replace = TRUE)) %>% 
  ungroup()
```


Row
-----------------------------------------------------------------------

### Trade Volume Development

```{r fig.width=15, fig.height=5}
data %>% 
  group_by(date) %>% 
  summarise(trade_volume = sum(trade_volume)) %>% 
  ggplot() +
  geom_line(aes(x = date, y = trade_volume), 
           color = "#2780e3",
           alpha = 0.8) +
  scale_y_continuous(labels = scales::dollar) +
  theme_minimal() +
  ylab("Trade Volume") +
  xlab("Date")
```


Row
-----------------------------------------------------------------------

### Product Group Share on Trade Volume

```{r}
data %>% 
  group_by(product_group) %>% 
  summarise(trade_volume = sum(trade_volume)) %>%
  mutate(trade_volume_share = trade_volume / sum(trade_volume)) %>% 
  ggplot() +
  geom_col(aes(x = reorder(product_group, -trade_volume_share), y = trade_volume_share), 
           fill = "#2780e3",
           alpha = 0.8) +
  scale_y_continuous(labels = scales::percent) +
  theme_minimal() +
  ylab("Share on Trade Volume") +
  xlab("Product Group")
```

### Product Group Share on Order Count

```{r}
data %>% 
  group_by(product_group) %>% 
  summarise(order_count = n()) %>% 
  mutate(order_count_share = order_count / sum(order_count)) %>% 
  ggplot() +
  geom_col(aes(x = reorder(product_group, -order_count_share), y = order_count_share), 
           fill = "#2780e3",
           alpha = 0.8) +
  scale_y_continuous(labels = scales::percent) +
  theme_minimal() +
  ylab("Share on Order Count") +
  xlab("Product Group")
```


```{r render subpages, include=FALSE}
# Get all unique product groups for the subpages
product_groups <- unique(data$product_group)

# Create variable which stores all subpages outputs
out = NULL

# Set knitr options to allow duplicate labels (needed for the subpages)
options(knitr.duplicate.label = 'allow')

# Create temporary environment which we use for knitting subpages.RMD 
subpage_env <- new.env()

for (pg in product_groups) {
  # Filter data for product group 
  subpage_data <- data %>% 
    filter(product_group == pg)
  
  # Assign filtered data and product group to subpage_env 
  assign("subpage_data", subpage_data, subpage_env)
  assign("product_group", pg, subpage_env)
  
  # Knit subpage.RMD using the subpage_env and add result to out vector
  out = c(out, knitr::knit_child('subpage.RMD', envir = subpage_env))
}
```

`r paste(knitr::knit_child(text = out), collapse = '')`


