<!DOCTYPE html>
<html lang="en-us">
<head>
  
  
  
  <script>
    (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-57MKRGQ');
  </script>
  
  

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="theme" content="hugo-academic">
  <meta name="generator" content="Hugo 0.44" />
  <meta name="author" content="Thomas Schmidt">

  
  
  
  
    
      
    
  
  <meta name="description" content="During this year’s summer break there had been a railway construction site which affected the train I usually use for commuting to work. This led to a lot of additional commuting time. Thus, I decided to repair my old mountain bike and give it a try to go to work by bike.
During the one hour ride I wondered how many people made the same decision and if there would be any data about Munich bike traffic with the use of which I could get some insights about Munich’s bike traffic.">

  
  <link rel="alternate" hreflang="en-us" href="/post/munich-bike-data-info-graphic/">

  


  

  
  
  <meta name="theme-color" content="#0095eb">
  
  
  
  
    
  
  
    
    
      
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css">
      
    
  
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha512-6MXa8B6uaO18Hid6blRMetEIoPqHf7Ux1tnyIQdpt9qI5OACx7C+O3IVTr98vwGnlcg0LOLa02i9Y1HpVhlfiw==" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.1/css/academicons.min.css" integrity="sha512-NThgw3XKQ1absAahW6to7Ey42uycrVvfNfyjqcFNgCmOCQ5AR4AO0SiXrN+8ZtYeappp56lk1WtvjVmEa+VR6A==" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha512-SfTiTlX6kk+qitfevl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw==" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.css" integrity="sha256-ygkqlh3CYSUri3LhQxzdcm0n1EQvH2Y+U5S2idbLtxs=" crossorigin="anonymous">
  
  
  
  
  <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Montserrat:400,700%7cRoboto:400,400italic,700%7cRoboto&#43;Mono">
  
  <link rel="stylesheet" href="/styles.css">
  

  

  
  <link rel="alternate" href="/index.xml" type="application/rss+xml" title="Somtom&#39;s Blog">
  <link rel="feed" href="/index.xml" type="application/rss+xml" title="Somtom&#39;s Blog">
  

  <link rel="manifest" href="/site.webmanifest">
  <link rel="icon" type="image/png" href="/img/icon.png">
  <link rel="apple-touch-icon" type="image/png" href="/img/icon-192.png">

  <link rel="canonical" href="/post/munich-bike-data-info-graphic/">

  <meta property="twitter:card" content="summary_large_image">
  <meta name="twitter:image" content="https://somtom.github.io/img/preview-images/munich-bike-data-infographic-preview.png" />
  
  <meta property="twitter:site" content="@somtom91">
  <meta property="twitter:creator" content="@somtom91">
  
  <meta property=“og:image“ content="https://somtom.github.io/img/preview-images/munich-bike-data-infographic-preview.png"/>
  <meta property="og:site_name" content="Somtom&#39;s Blog">
  <meta property="og:url" content="/post/munich-bike-data-info-graphic/">
  <meta property="og:title" content="Munich Bike Data Info Graphic | Somtom&#39;s Blog">
  <meta property="og:description" content="During this year’s summer break there had been a railway construction site which affected the train I usually use for commuting to work. This led to a lot of additional commuting time. Thus, I decided to repair my old mountain bike and give it a try to go to work by bike.
During the one hour ride I wondered how many people made the same decision and if there would be any data about Munich bike traffic with the use of which I could get some insights about Munich’s bike traffic."><meta property="og:image" content="/img/headers/munich-bike-data-infographic-header.png">
  <meta property="og:locale" content="en-us">
  
  <meta property="article:published_time" content="2018-11-03T00:00:00&#43;00:00">
  
  <meta property="article:modified_time" content="2018-11-03T00:00:00&#43;00:00">
  

  

  <title>Munich Bike Data Info Graphic | Somtom&#39;s Blog</title>

</head>
<body id="top" data-spy="scroll" data-target="#toc" data-offset="71" >
  
  
  
  <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-57MKRGQ"
  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
  

  

<nav class="navbar navbar-default navbar-fixed-top" id="navbar-main">
  <div class="container">

    
    <div class="navbar-header">
      
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
              data-target=".navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <a class="navbar-brand" href="/">Somtom&#39;s Blog</a>
    </div>

    
    <div class="collapse navbar-collapse">

      
      
      <ul class="nav navbar-nav navbar-right">
        

        
        
        
        
        
          
        

        <li class="nav-item">
          <a href="/#welcome">
            
            <span>Home</span>
            
          </a>
        </li>

        
        

        
        
        
        
        
          
        

        <li class="nav-item">
          <a href="/#about">
            
            <span>About</span>
            
          </a>
        </li>

        
        

        
        
        
        
        

        <li class="nav-item">
          <a href="/post">
            
            <span>Posts</span>
            
          </a>
        </li>

        
        

        
        
        
        
        
          
        

        <li class="nav-item">
          <a href="/#contact">
            
            <span>Contact</span>
            
          </a>
        </li>

        
        
      

      
      </ul>

    </div>
  </div>
</nav>


<article class="article" itemscope itemtype="http://schema.org/Article">

  
<div class="article-header">
  
  
    <img src="/img/./headers/munich-bike-data-infographic-header.png" class="article-banner" itemprop="image">
  

  
</div>



  <div class="article-container">
    <h1 itemprop="name">Munich Bike Data Info Graphic</h1>

    

<div class="article-metadata">

  <span class="article-date">
    
    <time datetime="2018-11-03 00:00:00 &#43;0000 UTC" itemprop="datePublished dateModified">
      Nov 3, 2018
    </time>
  </span>
  <span itemscope itemprop="author publisher" itemtype="http://schema.org/Person">
    <meta itemprop="name" content="Thomas Schmidt">
  </span>

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    26 min read
  </span>
  

  
  

  
  
  
  <span class="middot-divider"></span>
  <span class="article-categories">
    <i class="fa fa-folder"></i>
    
    <a href="/categories/analysis">Analysis</a
    >, 
    
    <a href="/categories/infographic">Infographic</a
    >
    
  </span>
  
  

  
  

  

</div>


    <div class="article-style" itemprop="articleBody">
      <div class="figure">
<img src="/rmarkdown-libs/infographic/insights_on_bike_traffic.png" />

</div>
<div id="analysis" style="display: none">
<hr />
<p>During this year’s summer break there had been a railway construction site which affected the train I usually use for commuting to work. This led to a lot of additional commuting time. Thus, I decided to repair my old mountain bike and give it a try to go to work by bike.<br />
During the one hour ride I wondered how many people made the same decision and if there would be any data about Munich bike traffic with the use of which I could get some insights about Munich’s bike traffic. Shortly after that, I happened to see a twitter post of <a href="https://twitter.com/opendata_muc/status/1039758780853104646">OpenData Munich</a> which announced a new data set containing the data of Munich’s 6 continuous bike counting stations for the years 2017 and 2018. The counting stations provide data such as 15-minute and daily bike counts for 2 directions.</p>
<p>I contacted the team in order to ask for additional information and received even more data as well as some nice inspirations. I picked up the idea of creating a info-graphic about Munich bike data. Thus, I had a new project and started the journey of designing my first info-graphic.</p>
<p>In this post we will go through the analysis behind the info-graphic you already saw above. We are going to answer questions such as:</p>
<ul>
<li><a href="#station_map">Can we create a map of all counting stations?</a></li>
<li><a href="#average_counts">What are average 15 minute and daily counts (across stations and per station)?</a></li>
<li><a href="#wrong_direction">How many people are driving in the wrong direction at Arnulf Street (this station is at a one-way road)?</a></li>
<li><a href="#count_records">What are the highest counts which had been measured?</a></li>
<li><a href="#bike_times">When are most people biking (time of the year, weather, …)?</a></li>
<li><a href="#commuting">How does the commuting traffic look like? Can we model it somehow and get some insights out of the data?</a></li>
</ul>
<p>If you want to skip the data import and jump directly to the preprocessing step, click <a href="#preprocessing">here</a>. To directly get into the analysis, click <a href="#analysis">here</a>.</p>
<h1 id="set-up-environment">Set up Environment</h1>
<p>First, as always, we load some packages needed for this analysis and create a custom theme to make the plots look nicer.</p>
<pre class="r"><code>suppressMessages({
  library(tidyverse)
  library(lubridate)
  library(geosphere)
  library(ggmap)
  library(reshape2)
  library(modelr)
  library(broom)
})

background_colors &lt;- c(&quot;#efedec&quot;, &quot;white&quot;)
plot_colors &lt;- c(&quot;#62c3db&quot;, &quot;#136d8f&quot;, &quot;#072d40&quot;, &quot;#f6a735&quot;, &quot;#fbd74d&quot;)
line_colors &lt;- c(&quot;black&quot;)

# Custom theme
my_theme &lt;- list(
 theme(
    plot.background = element_rect(fill =  background_colors[2]),
    text = element_text(color = line_colors),
    panel.background = element_rect(fill =  background_colors[2]),
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.line.y = element_line(color =  line_colors),
    axis.line.x = element_line(color =  line_colors),
    axis.ticks = element_line(color =  line_colors),
    axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0), color = line_colors),
    axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0), color = line_colors),
    legend.position = &quot;bottom&quot;,
    plot.margin = unit(c(0.5,1,0.5,0),&quot;cm&quot;),
    strip.background = element_rect(fill = &quot;white&quot;, color = &quot;black&quot;)
),
  scale_color_manual(
    values = plot_colors,
    guide = guide_legend(direction = &quot;horizontal&quot;, label.hjust = 0.5, title.position = &quot;top&quot;,
                              title.hjust = 0.5)),
  scale_fill_manual(
    values = plot_colors,
    guide = guide_legend(direction = &quot;horizontal&quot;, label.hjust = 0.5, title.position = &quot;top&quot;,
                              title.hjust = 0.5)))</code></pre>
<h1 id="import-data-from-api">Import Data from API</h1>
<p>Now, after setting everything up, we need to load the data. Since I got some additional data in <code>.csv</code> format, the importing happens in two steps:</p>
<ol style="list-style-type: decimal">
<li>We import the data from 2017 and 2018 via the Munich Open Data API</li>
<li>We import the additional data from <code>.csv</code> format</li>
</ol>
<h2 id="helper-functions">Helper Functions</h2>
<p>To fetch the data via API, I wrote some helper functions. This functions will also help us with the preprocessing later. The functions can be found in the <a href="https://github.com/Somtom/munich-bike-data-analysis">Github project</a>.</p>
<h2 id="fetch-data-from-api">(1) Fetch Data from API</h2>
<p>The following chunks will import the data for the years 2017 and 2018 (until end of July):</p>
<pre class="r"><code># Import muc_opd helper functions
# source(&quot;./muc-opd-helper-functions.R&quot;)

bike_counter_resource_id &lt;- &quot;211e882d-fadd-468a-bf8a-0014ae65a393&quot;
resource_ids &lt;- muc_odp_fetch_bike_count_resource_ids()

resource_ids_15_min &lt;- resource_ids$ids_15_min

resource_ids_daily &lt;- resource_ids$ids_daily</code></pre>
<pre class="r"><code>bike_counter &lt;- muc_odp_fetch_data(resource_id = bike_counter_resource_id, destination = &quot;./data/&quot;)

bike_cnt_15_min &lt;- bind_rows(
  lapply(resource_ids_15_min$resource_id, function(x) muc_odp_fetch_data(resource_id = x,
                                                             destination = &quot;./data/15_min/&quot;))
)

bike_cnt_day &lt;-  bind_rows(
  lapply(resource_ids_daily$resource_id, function(x) muc_odp_fetch_data(resource_id = x,
                                                             destination = &quot;./data/daily/&quot;))
)</code></pre>
<h2 id="add-additional-data">(2) Add Additional Data</h2>
<p>Now we import the additional data from the <code>.csv</code> files:</p>
<pre class="r"><code>files &lt;- list.files(&quot;./data/additional/&quot;, full.names = TRUE, recursive = TRUE)
files_15_min &lt;- stringr::str_detect(files, &quot;15Min&quot;)

suppressMessages({
  additional_15_min_data &lt;- bind_rows(lapply(files[files_15_min],
                                           read_csv2, 
                                           col_types = cols(.default = &quot;c&quot;)))
additional_daily_data &lt;- bind_rows(lapply(files[!files_15_min],
                                          read_csv2,
                                           col_types = cols(.default = &quot;c&quot;)))
})


# Change date column name to be equal to the API data
names(additional_15_min_data)[1] &lt;- &quot;datum&quot;
names(additional_daily_data)[1] &lt;- &quot;datum&quot;

bike_cnt_day &lt;- bind_rows(additional_daily_data, bike_cnt_day)
bike_cnt_15_min &lt;- bind_rows(additional_15_min_data, bike_cnt_15_min)</code></pre>
<h1 id="preprocessing">Preprocessing</h1>
<p>To prepare the data for the analysis we perform the following steps:</p>
<ol style="list-style-type: decimal">
<li>Convert data types (i.e. <code>character</code> to <code>POSIXct</code> for dates)</li>
<li>Gather the direction columns (<code>richtung_1</code> and <code>richtung_2</code>) into one <code>direction</code> column and convert their names to <code>'into center'</code> or <code>'out of center'</code> according to their direction relatively to the city center<br />
</li>
<li>Extract <code>weekday</code> information and add <code>weekend</code> indicator column</li>
<li>Remove duplicates (caused by the additional data)</li>
</ol>
<h2 id="convert-types">(1) Convert Types</h2>
<p>After importing the data, we need to convert its datatypes to a format which we can work with. We use the predefined helper functions for that.</p>
<pre class="r"><code>bike_counter &lt;- muc_odp_convert_bike_counter_types(bike_counter)
bike_cnt_15_min &lt;- muc_odp_convert_bike_cnt_15_min_types(bike_cnt_15_min)
bike_cnt_day &lt;- muc_odp_convert_bike_cnt_day_types(bike_cnt_day)</code></pre>
<h2 id="add-directions-information">(2) Add Directions Information</h2>
<p>All tables have two columns which are named <code>richtung_1</code> and <code>richtung_2</code>. These stand for the two different directions for which the stations measure the counts. In the <code>bike_counter</code> table we can find a description which tells us whether the given direction for that station is <code>east</code>, <code>weast</code>, <code>north</code> or <code>south</code>. We are going to convert the directions to either <code>into center</code> or <code>out of center</code> in order to gain more detailed information. In another helper function I precoded this information with a mapping function.</p>
<pre class="r"><code>bike_cnt_15_min &lt;- muc_odp_add_direction_info(bike_cnt_15_min)
bike_cnt_day &lt;- muc_odp_add_direction_info(bike_cnt_day)
bike_counter &lt;- muc_odp_add_direction_info(bike_counter)</code></pre>
<h2 id="extract-time-from-uhrzeit_start-english-time-start-and-add-weekend-indicator-column">(3) Extract Time from <code>uhrzeit_start</code> (English: Time Start) and Add Weekend Indicator Column</h2>
<p>In our last preprocessing step we add a <code>time</code> column to the 15 minutes table. This will hold the information on the <em>time of the day</em>. Further, we add the <code>weekday</code> as well as a indicator column which tells us whether the data were measured at the <code>weekend</code> or during the week.</p>
<pre class="r"><code>weekend_days &lt;- c(&quot;Sat&quot;, &quot;Sun&quot;)
bike_cnt_15_min &lt;- bike_cnt_15_min %&gt;% 
  mutate(time = as.numeric(uhrzeit_start - trunc(uhrzeit_start, &quot;days&quot;)),
         weekday = wday(uhrzeit_start, label = TRUE, local = &quot;us&quot;),
         weekend = factor(weekday %in% weekend_days)) 

bike_cnt_day &lt;- bike_cnt_day %&gt;% 
  mutate(weekday = factor(wday(datum, label = TRUE, local = &quot;us&quot;)),
         weekend = factor(weekday %in% weekend_days))

class(bike_cnt_15_min$time) &lt;- &quot;POSIXct&quot;</code></pre>
<h2 id="remove-duplicates-and-save-converted-data">(4) Remove Duplicates and Save Converted Data</h2>
<p>Finally, we remove the duplicates from our data set and save the converted data.</p>
<pre class="r"><code>bike_cnt_15_min &lt;- unique(bike_cnt_15_min)</code></pre>
<pre class="r"><code>saveRDS(bike_counter, &quot;./2018-11-03-munich-bike-data-info-graphic_files/bike_counter_converted.RDS&quot;)
saveRDS(bike_cnt_15_min, &quot;./2018-11-03-munich-bike-data-info-graphic_files/bike_cnt_15_min_converted.RDS&quot;)
saveRDS(bike_cnt_day, &quot;./2018-11-03-munich-bike-data-info-graphic_files/bike_cnt_day_converted.RDS&quot;)</code></pre>
<h1 id="analysis">Analysis</h1>
<p>Now that we are done with preprocessing, we can start with our analysis.</p>
<h2 id="time-period-of-our-data-set">Time Period of Our Data Set</h2>
<p>First, lets have a look at the time period we are analyzing:</p>
<pre class="r"><code>cat(paste0(
  &#39;## 15 Minute Data ##&#39;,
  &#39;\nStart:\t&#39;, min(bike_cnt_15_min$datum),
  &#39;\nEnd:\t&#39;, max(bike_cnt_15_min$datum), 
  &#39;\n\n## Daily Data ##&#39;,
  &#39;\nStart:\t&#39;, min(bike_cnt_day$datum),
  &#39;\nEnd:\t&#39;, max(bike_cnt_day$datum)))</code></pre>
<pre><code>## ## 15 Minute Data ##
## Start:   2008-06-01
## End: 2018-07-31
## 
## ## Daily Data ##
## Start:   2008-06-01
## End: 2018-07-31</code></pre>
<h2 id="missing-data">Missing Data</h2>
<p>Very important for every analysis is to be aware of missing data. So let’s have a look at our data:</p>
<pre class="r"><code>bike_cnt_day %&gt;% 
  map(function(x) sum(is.na(x))) %&gt;% 
  bind_cols %&gt;%
  melt(value.name = &quot;na_count&quot;, variable.name = &quot;column&quot;) %&gt;% 
  filter(na_count &gt; 0) %&gt;% knitr::kable(digits = 2)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">column</th>
<th align="right">na_count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">bewoelkung</td>
<td align="right">25308</td>
</tr>
<tr class="even">
<td align="left">sonnenstunden</td>
<td align="right">25308</td>
</tr>
<tr class="odd">
<td align="left">niederschlag</td>
<td align="right">25308</td>
</tr>
<tr class="even">
<td align="left">max_temp</td>
<td align="right">25308</td>
</tr>
<tr class="odd">
<td align="left">min_temp</td>
<td align="right">25308</td>
</tr>
<tr class="even">
<td align="left">id</td>
<td align="right">37512</td>
</tr>
</tbody>
</table>
<p>We see that some weather data and ids are missing for the <code>bike_cnt_day</code> table. These missing values are all from our additional data. Important is that we need to take this into account when we draw conclusions later.</p>
<pre class="r"><code>bike_cnt_15_min %&gt;% 
  map(function(x) sum(is.na(x))) %&gt;% 
  bind_cols %&gt;%
  melt(value.name = &quot;na_count&quot;, variable.name = &quot;column&quot;) %&gt;% 
  filter(na_count &gt; 0) %&gt;% dim()</code></pre>
<pre><code>## [1] 0 2</code></pre>
<p>No data are missing for <code>bike_cnt_15_min</code> table.</p>
<h2 id="station_map">Map of Stations</h2>
<p>To get a first overview of the locations of the 6 counting stations, we create a map of Munich using the <code>ggmap</code> package and add markers for each station.</p>
<pre class="r"><code>area &lt;- make_bbox(lon = longitude, lat = latitude, data = bike_counter)
area &lt;- area + c(-0.02, -0.01, 0.01, 0.01)

suppressMessages({area_map &lt;- get_map(area,  source = &quot;stamen&quot;)})

ggmap(area_map, extend = &quot;device&quot;, darken = 0.3,
      base_layer = ggplot(aes(x = longitude, y = latitude), data = bike_counter)) +
  geom_point(shape = 21, size = 4, fill = plot_colors[1]) +
  geom_text(aes(label = zaehlstelle), vjust = -1, color = &quot;white&quot;) +
  theme_void()</code></pre>
<p><img src="/post/2018-11-03-munich-bike-data-info-graphic_files/figure-html/map-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>The stations are spread across Munich. Their locations were planned to be as different as possible but also representative for typical traffic situations (<em>Zorn et. al 2011</em>).</p>
<h2 id="compare-the-data-of-all-stations">Compare the Data of All Stations</h2>
<h3 id="average_counts">What Are Average 15 Minute and Daily Counts?</h3>
<p>Now that we have a bird’s eye view on the locations, let’s get an overview on the data by looking at summary stats like average, median and others. First, we start with a summary across all stations. For this purpose we use the <code>summary()</code> function combined with <code>tidy()</code> from the <code>broom</code> package to get everything in one table.</p>
<pre class="r"><code>bind_rows(
  c(
    table = &quot;bike_cnt_day&quot;,
    broom::tidy(summary(bike_cnt_day$gesamt)), 
    sd = sd(bike_cnt_day$gesamt)),
  c(
    table = &quot;bike_cnt_15_min&quot;, 
    broom::tidy(summary(bike_cnt_15_min$gesamt)),
    sd = sd(bike_cnt_15_min$gesamt)))  %&gt;% knitr::kable(digits = 2)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">table</th>
<th align="right">minimum</th>
<th align="right">q1</th>
<th align="right">median</th>
<th align="right">mean</th>
<th align="right">q3</th>
<th align="right">maximum</th>
<th align="right">sd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">bike_cnt_day</td>
<td align="right">0</td>
<td align="right">305</td>
<td align="right">862</td>
<td align="right">1352.91</td>
<td align="right">1916</td>
<td align="right">15009</td>
<td align="right">1471.79</td>
</tr>
<tr class="even">
<td align="left">bike_cnt_15_min</td>
<td align="right">-2</td>
<td align="right">0</td>
<td align="right">4</td>
<td align="right">13.86</td>
<td align="right">17</td>
<td align="right">1157</td>
<td align="right">23.43</td>
</tr>
</tbody>
</table>
<p>On average the stations count <strong>14 bike per 15 minutes</strong> and <strong>1353 bikes per day</strong>. When we have a look at the maxima, we see that they are quiet high compared to the means. Especially the 15 minute count maximum is <strong>83</strong> times as high as the mean. We might find some interesting events being represented by these high counts but we will dive deeper into that later.</p>
<p>How does the summary data differ if we calculate it per station? We first start with the 15 minute data. To compare the stations we additionally calculate a <code>scaled_median_count</code> which is the median for a single station divided by the minimum of all station medians.</p>
<pre class="r"><code>station_summary_15_min &lt;- bike_cnt_15_min %&gt;% 
  spread(key = direction, value = count) %&gt;% 
  group_by(zaehlstelle) %&gt;% 
  summarise(avg = round(mean(gesamt, na.rm = T)),
            median_count = median(gesamt, na.rm = T),
            q1 = quantile(gesamt, 0.25, na.rm = T),
            q3 = quantile(gesamt, 0.75, na.rm = T),
            sd = sd(gesamt, na.rm = T),
            percent_sd = round(sd/median_count * 100, 2)) %&gt;% 
  ungroup() %&gt;% 
  mutate(scaled_median_count = round(median_count / min(median_count))) %&gt;% 
  arrange(desc(median_count)) 

station_summary_15_min  %&gt;% knitr::kable(digits = 2)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">zaehlstelle</th>
<th align="right">avg</th>
<th align="right">median_count</th>
<th align="right">q1</th>
<th align="right">q3</th>
<th align="right">sd</th>
<th align="right">percent_sd</th>
<th align="right">scaled_median_count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Erhardt</td>
<td align="right">34</td>
<td align="right">19</td>
<td align="right">5</td>
<td align="right">50</td>
<td align="right">40.17</td>
<td align="right">211.42</td>
<td align="right">19</td>
</tr>
<tr class="even">
<td align="left">Margareten</td>
<td align="right">25</td>
<td align="right">15</td>
<td align="right">3</td>
<td align="right">39</td>
<td align="right">26.98</td>
<td align="right">179.87</td>
<td align="right">15</td>
</tr>
<tr class="odd">
<td align="left">Arnulf</td>
<td align="right">11</td>
<td align="right">6</td>
<td align="right">1</td>
<td align="right">16</td>
<td align="right">14.39</td>
<td align="right">239.76</td>
<td align="right">6</td>
</tr>
<tr class="even">
<td align="left">Olympia</td>
<td align="right">14</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">20</td>
<td align="right">20.61</td>
<td align="right">412.13</td>
<td align="right">5</td>
</tr>
<tr class="odd">
<td align="left">Hirsch</td>
<td align="right">6</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">8</td>
<td align="right">10.68</td>
<td align="right">1068.43</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">Kreuther</td>
<td align="right">3</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">4</td>
<td align="right">4.82</td>
<td align="right">482.46</td>
<td align="right">1</td>
</tr>
</tbody>
</table>
<p>As we see, Erhardt is the station with the highest median 15 minute count (19 bikes). Its median is 19 times higher than the one of Kreuther. Nevertheless, the standard deviation is very high across all stations, which is an indicator for a lot of intra day deviation.</p>
<p>How does the per station summary look like for the daily counts?</p>
<pre class="r"><code>station_summary_day &lt;- bike_cnt_day %&gt;% 
  spread(key = direction, value = count) %&gt;% 
  group_by(zaehlstelle) %&gt;% 
  summarise(avg = round(mean(gesamt)),
            median_count = median(gesamt),
            q1 = quantile(gesamt, 0.25),
            q3 = quantile(gesamt, 0.75),
            sd = sd(gesamt),
            percent_sd = round(sd/median_count * 100,2)) %&gt;% 
  ungroup() %&gt;% 
  mutate(scaled_median_count = round(median_count / min(median_count))) %&gt;% 
  arrange(desc(median_count)) 

station_summary_day  %&gt;% knitr::kable(digits = 2)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">zaehlstelle</th>
<th align="right">avg</th>
<th align="right">median_count</th>
<th align="right">q1</th>
<th align="right">q3</th>
<th align="right">sd</th>
<th align="right">percent_sd</th>
<th align="right">scaled_median_count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Erhardt</td>
<td align="right">3291</td>
<td align="right">2862.0</td>
<td align="right">1646.00</td>
<td align="right">4725.00</td>
<td align="right">2080.50</td>
<td align="right">72.69</td>
<td align="right">13</td>
</tr>
<tr class="even">
<td align="left">Margareten</td>
<td align="right">2385</td>
<td align="right">2322.0</td>
<td align="right">1340.00</td>
<td align="right">3277.00</td>
<td align="right">1307.51</td>
<td align="right">56.31</td>
<td align="right">10</td>
</tr>
<tr class="odd">
<td align="left">Olympia</td>
<td align="right">1332</td>
<td align="right">1156.0</td>
<td align="right">543.50</td>
<td align="right">1891.00</td>
<td align="right">1077.79</td>
<td align="right">93.23</td>
<td align="right">5</td>
</tr>
<tr class="even">
<td align="left">Arnulf</td>
<td align="right">1050</td>
<td align="right">896.5</td>
<td align="right">474.25</td>
<td align="right">1412.75</td>
<td align="right">792.05</td>
<td align="right">88.35</td>
<td align="right">4</td>
</tr>
<tr class="odd">
<td align="left">Hirsch</td>
<td align="right">615</td>
<td align="right">488.5</td>
<td align="right">141.25</td>
<td align="right">903.75</td>
<td align="right">590.32</td>
<td align="right">120.84</td>
<td align="right">2</td>
</tr>
<tr class="even">
<td align="left">Kreuther</td>
<td align="right">283</td>
<td align="right">223.0</td>
<td align="right">89.00</td>
<td align="right">400.00</td>
<td align="right">252.36</td>
<td align="right">113.17</td>
<td align="right">1</td>
</tr>
</tbody>
</table>
<p>We see a similar picture compared to the 15 minute data. With a median daily bike count of 2862, station Erhardt has the highest daily counts, too. This time the count is 13 higher than the count of Kreuther.</p>
<h3 id="wrong_direction">How Many People Are Riding in the Wrong Direction at Arnulf Street?</h3>
<p>Station <strong>Arnulf Street</strong> has a special characteristic: The counter is located on a one way bicycle lane. Thus, normally it should only measure counts for one direction, which is into city center.</p>
<p>Luckily it is also able to count all bikers who ride into the wrong direction, which we can use for our analysis. So let’s find out which share of the total counts is due to bikers riding the wrong direction.</p>
<pre class="r"><code>wrong_way_drivers &lt;- bike_cnt_day %&gt;% 
  filter(zaehlstelle == &quot;Arnulf&quot;) %&gt;%
  filter(direction == &quot;out of center&quot;) %&gt;%
  mutate(share = round(count / gesamt * 100, 2)) %&gt;% 
  select(share) %&gt;% unlist() %&gt;% summary() %&gt;% tidy()
wrong_way_drivers  %&gt;% knitr::kable(digits = 2)</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">minimum</th>
<th align="right">q1</th>
<th align="right">median</th>
<th align="right">mean</th>
<th align="right">q3</th>
<th align="right">maximum</th>
<th align="right">na</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0</td>
<td align="right">3.91</td>
<td align="right">5.1</td>
<td align="right">5.8</td>
<td align="right">6.68</td>
<td align="right">100</td>
<td align="right">101</td>
</tr>
</tbody>
</table>
<p>The data suggests that on average <strong>5.8 percent</strong> of daily counted bikes at Arnulf Street were driving on the <strong>wrong side of the road</strong>. Interestingly, there must have been at least one day where all bikes were riding on the wrong side of the road since we observed a maximum of 100%.</p>
<h2 id="count_records">Count Records</h2>
<p>Now it is time to come back to the maximum counts we recognized earlier. To get a quick overview before we dive into the story behind some maximum counts, let’s create a top 10 list for both the daily and the 15 minute counts:</p>
<pre class="r"><code># Daily Counts
top_10_day &lt;- bike_cnt_day %&gt;% 
  spread(key = direction, value = count) %&gt;% 
  arrange(desc(gesamt)) %&gt;% 
  head(10)

top_10_day %&gt;% 
  select(datum, gesamt, zaehlstelle) %&gt;% 
  knitr::kable(digits = 2)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">datum</th>
<th align="right">gesamt</th>
<th align="left">zaehlstelle</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">2012-06-09</td>
<td align="right">15009</td>
<td align="left">Olympia</td>
</tr>
<tr class="even">
<td align="left">2010-06-26</td>
<td align="right">14714</td>
<td align="left">Olympia</td>
</tr>
<tr class="odd">
<td align="left">2010-06-27</td>
<td align="right">12241</td>
<td align="left">Olympia</td>
</tr>
<tr class="even">
<td align="left">2013-06-19</td>
<td align="right">9296</td>
<td align="left">Erhardt</td>
</tr>
<tr class="odd">
<td align="left">2018-07-26</td>
<td align="right">9228</td>
<td align="left">Erhardt</td>
</tr>
<tr class="even">
<td align="left">2017-07-05</td>
<td align="right">9207</td>
<td align="left">Erhardt</td>
</tr>
<tr class="odd">
<td align="left">2018-07-24</td>
<td align="right">9179</td>
<td align="left">Erhardt</td>
</tr>
<tr class="even">
<td align="left">2016-06-23</td>
<td align="right">9113</td>
<td align="left">Erhardt</td>
</tr>
<tr class="odd">
<td align="left">2016-07-20</td>
<td align="right">9106</td>
<td align="left">Erhardt</td>
</tr>
<tr class="even">
<td align="left">2018-06-20</td>
<td align="right">9106</td>
<td align="left">Erhardt</td>
</tr>
</tbody>
</table>
<p>That is interesting: Station Olympia takes the top 3 places with counts above 10 thousand, although it only made the third place when we calculated the median counts per station earlier. After some research I found out that these top 3 counts were caused by the same event, namely the <strong>24h Mountainbike Race</strong>, which takes place in Olympia Park every year. Since the route is changed from year to year, the counting station is not always on the track. Thus, we don’t see these record counts every year.</p>
<p>Let’s plot the 15 minute data for the events in the two years in which we observed these high counts:</p>
<p><img src="/post/2018-11-03-munich-bike-data-info-graphic_files/figure-html/plot_mtb_race-1.png" width="960" style="display: block; margin: auto;" /><img src="/post/2018-11-03-munich-bike-data-info-graphic_files/figure-html/plot_mtb_race-2.png" width="960" style="display: block; margin: auto;" /></p>
<p>Now we also create a top 10 list for the 15 minute counts:</p>
<pre class="r"><code># 15 Minute Counts
top_10_15_min &lt;- bike_cnt_15_min %&gt;% 
  spread(key = direction, value = count) %&gt;% 
  arrange(desc(gesamt)) %&gt;% 
  head(10)

top_10_15_min  %&gt;% 
  select(datum, gesamt, uhrzeit_start, zaehlstelle) %&gt;% knitr::kable(digits = 2)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">datum</th>
<th align="right">gesamt</th>
<th align="left">uhrzeit_start</th>
<th align="left">zaehlstelle</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">2017-09-03</td>
<td align="right">1157</td>
<td align="left">2017-09-03 13:45:00</td>
<td align="left">Olympia</td>
</tr>
<tr class="even">
<td align="left">2017-09-03</td>
<td align="right">945</td>
<td align="left">2017-09-03 14:00:00</td>
<td align="left">Olympia</td>
</tr>
<tr class="odd">
<td align="left">2015-05-10</td>
<td align="right">540</td>
<td align="left">2015-05-10 12:30:00</td>
<td align="left">Olympia</td>
</tr>
<tr class="even">
<td align="left">2015-05-10</td>
<td align="right">503</td>
<td align="left">2015-05-10 12:15:00</td>
<td align="left">Olympia</td>
</tr>
<tr class="odd">
<td align="left">2015-05-10</td>
<td align="right">455</td>
<td align="left">2015-05-10 12:45:00</td>
<td align="left">Olympia</td>
</tr>
<tr class="even">
<td align="left">2016-10-16</td>
<td align="right">421</td>
<td align="left">2016-10-16 13:45:00</td>
<td align="left">Olympia</td>
</tr>
<tr class="odd">
<td align="left">2016-10-16</td>
<td align="right">409</td>
<td align="left">2016-10-16 14:00:00</td>
<td align="left">Olympia</td>
</tr>
<tr class="even">
<td align="left">2015-05-10</td>
<td align="right">385</td>
<td align="left">2015-05-10 12:00:00</td>
<td align="left">Olympia</td>
</tr>
<tr class="odd">
<td align="left">2012-06-09</td>
<td align="right">365</td>
<td align="left">2012-06-09 23:00:00</td>
<td align="left">Olympia</td>
</tr>
<tr class="even">
<td align="left">2015-05-10</td>
<td align="right">363</td>
<td align="left">2015-05-10 14:45:00</td>
<td align="left">Olympia</td>
</tr>
</tbody>
</table>
<p>If we have a closer look, we only can find one of our daily count top 10 candidates in this list, namely the <strong>2017-06-09</strong> on the 6th place. Normally you would suppose the date with highest 15 minute counts to also be listed in the daily count top 10 unless the high counts were due to a short time event. So what happened on the 3rd September 2017 when a 15 minute bike count of <strong>1157</strong> was recorded?</p>
<p>This picture from <a href="https://radlhauptstadt.muenchen.de/">radlhaupstadt.muenchen.de</a> gives you a hint:</p>
<div class="figure">
<img src="/rmarkdown-libs/img/ringparade.jpg" alt="Picture source: radlhauptstadt.muenchen.de" />
<p class="caption">Picture source: radlhauptstadt.muenchen.de</p>
</div>
<p>On that day the so called <a href="https://radlhauptstadt.muenchen.de/mitradeln/muenchner-ringparade/">Münchner Ringparade</a> took place. At this event the Munich beltway had been closed temporarily for car traffic while round about 7000 people used this route for a bike tour. The 12 km tour ended in Olympia Park. And this is exactly what we can see in the data:</p>
<p><img src="/post/2018-11-03-munich-bike-data-info-graphic_files/figure-html/olympia_record_plot-1.png" width="960" style="display: block; margin: auto;" /></p>
<h2 id="bike_times">When Are Most People Biking?</h2>
<h3 id="pattern-across-a-year">Pattern Across a Year</h3>
<p>To answer this question we first try to gain an overview by plotting the development of the daily counts over the years</p>
<p><img src="/post/2018-11-03-munich-bike-data-info-graphic_files/figure-html/daily_count_over_years-1.png" width="864" style="display: block; margin: auto;" /></p>
<p>There is definitely a clear seasonal pattern which is similar across all stations. As one would expect, there are higher bike counts during the summer months and lower counts during winter months. However, we also see individual trends or characteristics for some stations:</p>
<ul>
<li>Station <strong>Hirsch</strong> shows a ongoing trend of rising bike counts from year to year</li>
<li>At <strong>Arnulf Street’s</strong> counting station one can see two peak years in 2013 and 2014. These peaks could be due to a railway construction site which affected parts of the trains going into city center.</li>
<li>Station <strong>Kreuther</strong> showed some high counts at the beginning of 2013 and then no data for the rest of the year. Here the counting station was affected by a construction site when a separate bicycle path was created. After that, bikes on the sidewalk were not counted anymore. This is why daily bike count level dropped afterwards.</li>
<li>One can clearly see the events taking place in <strong>Olympia Park</strong> represented by peaks in the data</li>
</ul>
<p>When we plot the bike count distribution for each month, we see that <strong>highest median bike counts occur in the month July</strong>. However, the maximum counts had been recorded in June. These are due to some of the record events mentioned earlier, though. Thus, they need to be interpreted as outliers</p>
<p><img src="/post/2018-11-03-munich-bike-data-info-graphic_files/figure-html/daily_count_month_wise_distribution-1.png" width="960" style="display: block; margin: auto;" /></p>
<h3 id="day-of-the-week">Day of the Week</h3>
<p>When we look at the distribution of total daily counts, we see that counts <strong>during the week</strong> are <strong>higher than those at the weekends</strong>. This is most likely due to commuting traffic, which we will try to model later. The maximum counts occurred on Saturdays but are due to single events like the 24h Mountain-bike race we saw earlier.</p>
<p><img src="/post/2018-11-03-munich-bike-data-info-graphic_files/figure-html/bike_count_distribution_week-1.png" width="960" style="display: block; margin: auto;" /></p>
<h3 id="temperature-and-weather-on-days-with-maximum-counts">Temperature and Weather on Days with Maximum Counts</h3>
<p>Now we use the weather data we have (at least for the days where they are not missing) and try to characterize the days with highest bike counts. We look at the distribution of measured values within each weather variable <strong>for the month July</strong>.</p>
<p>To do so we group the bike counts into 4 categories:</p>
<ul>
<li><strong>Lowest 25%:</strong> Daily bike counts which lie between the <strong>minimum</strong> count and the <strong>25% percentile</strong></li>
<li><strong>Lower Middle:</strong> Daily bike counts which lie between the <strong>25% percentile</strong> and the <strong>median</strong></li>
<li><strong>Upper Middle:</strong> Daily bike counts which lie between the <strong>median</strong> and the <strong>75% percentile</strong></li>
<li><strong>Highest 25%:</strong> Daily bike counts which lie between the <strong>75% percentile</strong> and the <strong>maximum</strong></li>
</ul>
<p>We then will have a closer look into the <strong>“Highest 25%”</strong> group and the weather parameters measured on these days.</p>
<p>To make the data comparable between stations, we perform the following steps:</p>
<ol style="list-style-type: decimal">
<li>Removing outliers by filtering for bike counts below the 99% percentile for each station<br />
</li>
<li>Scaling the daily counts from each station by dividing the counts by each station’s maximum count<br />
</li>
<li>Using the scaled counts (values between 0 and 1) to assign bike count categories</li>
</ol>
<pre class="r"><code>breaks &lt;- bike_cnt_day %&gt;% 
  filter(month(datum) == 7) %&gt;% 
  spread(key = direction, value = count) %&gt;%
  group_by(zaehlstelle) %&gt;% 
  # Calculate 99% percentile per station in order to filter outlieres 
  mutate(percentile_99 = quantile(gesamt, 0.99))  %&gt;%
  filter(gesamt &lt; percentile_99) %&gt;% 
  # Scale to make compareable across stations
  mutate(gesamt_scaled = gesamt / max(gesamt)) %&gt;% 
  ungroup() %&gt;% 
  # Create count classes
  summarise(count_q1 = quantile(gesamt_scaled, 0.25),
         count_q2 = quantile(gesamt_scaled, 0.5),
         count_q3 = quantile(gesamt_scaled, 0.75),
         max_count = max(gesamt_scaled)) %&gt;% unlist()

labels &lt;- c(&quot;Lowest 25%\n[0-q1]&quot;, 
            &quot;Lower Middle\n(q1-q2]&quot;,
            &quot;Upper Middle\n(q2-q3]&quot;, 
            &quot;Highest 25%\n(q3-max]&quot;)

bike_cnt_day_july_scaled &lt;- bike_cnt_day %&gt;% 
  filter(month(datum) == 7) %&gt;% 
  spread(key = direction, value = count) %&gt;%
  group_by(zaehlstelle) %&gt;% 
  # Calculate 99% percentile per station in order to filter outlieres 
  mutate(percentile_99 = quantile(gesamt, 0.99))  %&gt;%
  filter(gesamt &lt; percentile_99) %&gt;% 
  # Scale to make compareable across stations
  mutate(gesamt_scaled = gesamt / max(gesamt)) %&gt;% 
  ungroup() %&gt;% 
  mutate(cat = cut(gesamt_scaled, breaks = c(0, breaks), include.lowest = T, labels = labels)) %&gt;%
  select(cat, bewoelkung, sonnenstunden, niederschlag, max_temp, min_temp)</code></pre>
<p><img src="/post/2018-11-03-munich-bike-data-info-graphic_files/figure-html/temperature_and_weather_distribution_for_maximum_days-1.png" width="960" style="display: block; margin: auto;" /></p>
<p>When we look at each weather parameter, we can see differences in value distributions between the 4 bike count categories. However these differences are not always that clear. But, there are at least trends for all parameters except one, namely the minimum temperature, where mostly the variance differs. The other parameters don’t show great surprises: You would, for example, expect the precipitation to be very low on days with a lot of bikes being counted.</p>
<p>In order to get some numbers to describe the days with highest counts, let’s look into a summary for each weather category at days with bike counts within the “Highest 25%” group in July.</p>
<pre class="r"><code>get_mode &lt;- function(x) {
  ux &lt;- na.omit(unique(x))
  tab &lt;- tabulate(match(x, ux))
  ux[tab == max(tab)][1]
}

# Characterise the metrics for the maximum category within july
bike_cnt_day_july_scaled %&gt;% 
  group_by(cat) %&gt;% 
  summarise(max_temp = list(cbind(broom::glance(summary(max_temp)), mode = get_mode(max_temp))),
            min_temp = list(cbind(broom::glance(summary(min_temp)), mode = get_mode(min_temp))),
            bewoelkung = list(cbind(broom::glance(summary(bewoelkung)), mode = get_mode(bewoelkung))),
            sonnenstunden = list(cbind(broom::glance(summary(sonnenstunden)), mode = get_mode(sonnenstunden))),
            niederschlag = list(cbind(broom::glance(summary(niederschlag)), mode = get_mode(niederschlag)))) %&gt;%
  gather(key = metric, value = value, -cat)  %&gt;% 
  unnest() %&gt;%   
  filter(cat == &quot;Highest 25%\n(q3-max]&quot;) %&gt;% mutate(metric = plyr::revalue(metric, 
                                c(&quot;bewoelkung&quot; = &quot;Cloudiness [%]&quot;,
                                  &quot;max_temp&quot; = &quot;Maximum Temperature [°C]&quot;,
                                  &quot;min_temp&quot; = &quot;Minimum Temperature [°C]&quot;,
                                  &quot;niederschlag&quot; = &quot;Precipitation  [ml]&quot;,
                                  &quot;sonnenstunden&quot; = &quot;Hours of Sunshine [h]&quot;))) %&gt;% 
  select(-na, -cat)  %&gt;% knitr::kable(digits = 2)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">metric</th>
<th align="right">minimum</th>
<th align="right">q1</th>
<th align="right">median</th>
<th align="right">mean</th>
<th align="right">q3</th>
<th align="right">maximum</th>
<th align="right">mode</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Maximum Temperature [°C]</td>
<td align="right">19.8</td>
<td align="right">26.0</td>
<td align="right">28.2</td>
<td align="right">28.24</td>
<td align="right">30.6</td>
<td align="right">36.9</td>
<td align="right">28.2</td>
</tr>
<tr class="even">
<td align="left">Minimum Temperature [°C]</td>
<td align="right">10.3</td>
<td align="right">13.7</td>
<td align="right">15.7</td>
<td align="right">15.62</td>
<td align="right">17.4</td>
<td align="right">21.5</td>
<td align="right">17.5</td>
</tr>
<tr class="odd">
<td align="left">Cloudiness [%]</td>
<td align="right">0.0</td>
<td align="right">19.0</td>
<td align="right">40.0</td>
<td align="right">43.73</td>
<td align="right">71.0</td>
<td align="right">95.0</td>
<td align="right">75.0</td>
</tr>
<tr class="even">
<td align="left">Hours of Sunshine [h]</td>
<td align="right">2.8</td>
<td align="right">8.1</td>
<td align="right">12.0</td>
<td align="right">10.89</td>
<td align="right">13.4</td>
<td align="right">15.6</td>
<td align="right">14.3</td>
</tr>
<tr class="odd">
<td align="left">Precipitation [ml]</td>
<td align="right">0.0</td>
<td align="right">0.0</td>
<td align="right">0.0</td>
<td align="right">1.05</td>
<td align="right">0.2</td>
<td align="right">16.9</td>
<td align="right">0.0</td>
</tr>
</tbody>
</table>
<p>Great! We can take these median values for the info-graphic to give a statement for a typical biking day:</p>
<p><em>Days with highest counts lie in <strong>July</strong>. The temperature on these days is <strong>15.7 - 28.2°C</strong> and the <strong>sun</strong> is shining for <strong>12 hours</strong> with <strong>scattered clouds</strong> but <strong>without</strong> any <strong>precipitation.</strong></em></p>
<h2 id="commuting">Modeling Commuting Traffic</h2>
<h3 id="differences-between-weekend-counts-and-counts-during-week">Differences Between Weekend Counts and Counts During Week</h3>
<p>We already got some nice information about the bike traffic in Munich. Our next aim is to use the 15 minute data to model the commuting traffic. We start with a bird’s eye overview by plotting the median 15 minute counts across all stations for weekend and working days.</p>
<p><img src="/post/2018-11-03-munich-bike-data-info-graphic_files/figure-html/15_min_plot_weekend_week-1.png" width="960" style="display: block; margin: auto;" /></p>
<p>We can see that the 15 minute count patterns clearly differ between weekend days and week days. There are two clear commuting peaks during the week. However, there still seems to be regular traffic between these peaks.<br />
We used the median 15 minute bike count across all stations for the previous plot. But, will we still see the same pattern if we look at each station separately?</p>
<p><img src="/post/2018-11-03-munich-bike-data-info-graphic_files/figure-html/15_min_plot_weekend_week_per_station-1.png" width="1248" style="display: block; margin: auto;" /></p>
<p>Indeed, the pattern is similar across all stations. Nevertheless, stations show different commuting direction characteristics. The stations can be assigned to either one of these 3 groups:</p>
<ol style="list-style-type: decimal">
<li>Station with traffic mainly in the direction of the city center in the morning and back way in the afternoon:
<ul>
<li>Erhardt</li>
<li>Hirsch</li>
</ul></li>
<li>Stations with traffic mainly out of the city center in the morning and back in the afternoon
<ul>
<li>Kreuther</li>
<li>Margareten</li>
</ul></li>
<li>Stations with similar patterns for traffic into- and out of city center
<ul>
<li>Olympia</li>
</ul></li>
</ol>
<p>We cannot really tell for Arnulf Street but it looks like the peaks in the morning and in the afternoon are similar for the only measured direction (into center). This would make it fall into class 3.</p>
<h3 id="the-model">The Model</h3>
<p>To create a really basic model of the commuting traffic, we make the following assumption: <em>Traffic during week is the result of commuting traffic and the normal traffic which is represented by the weekend data.</em> Under this assumption subtracting the 15 minute weekend counts from the 15 minute counts during the week gives us the commuting part. We are going to create a <code>loess</code> model for each the weekend and the week counts for that purpose.</p>
<pre class="r"><code>bike_cnt_15_min_separated &lt;- bike_cnt_15_min %&gt;% 
  mutate(Weekend = factor(ifelse(weekend == TRUE, &quot;Weekend&quot;, &quot;Week&quot;))) %&gt;% 
  group_by(Weekend, time) %&gt;% 
  summarise(median = median(gesamt)) %&gt;% 
  spread(key = Weekend, value = median) %&gt;% 
  mutate(Commuting = Week - Weekend) %&gt;% 
  gather(key = week_cat, value = median_count, Commuting, Weekend, Week) %&gt;% 
  mutate(week_cat = factor(week_cat, levels = c(&quot;Weekend&quot;, &quot;Week&quot;, &quot;Commuting&quot;)),
         commuting_cat = factor(ifelse(week_cat == &quot;Commuting&quot;,
                                       &quot;Commuting Traffic&quot;,
                                       &quot;Normal Traffic&quot;),
                                levels = c(&quot;Normal Traffic&quot;, &quot;Commuting Traffic&quot;))) 

tmp &lt;- bike_cnt_15_min_separated %&gt;% 
  mutate(median_count = ifelse(median_count &lt; 0, 0, median_count),
         x = as.numeric(time)) 

fit_commuting &lt;- loess(median_count~x, data = tmp, subset = c(tmp$week_cat == &quot;Commuting&quot;), span = 0.2)
fit_weekend &lt;- loess(median_count~x, data = tmp, subset = c(tmp$week_cat == &quot;Weekend&quot;), span = 0.2)
fit_week &lt;- loess(median_count~x, data = tmp, subset = c(tmp$week_cat == &quot;Week&quot;), span = 0.2)

bike_cnt_15_min_modeled &lt;- data.frame(x = seq(min(tmp$x), max(tmp$x)), 60) %&gt;% 
  add_predictions(fit_commuting, &quot;pred_commuting&quot;) %&gt;%
  add_predictions(fit_weekend, var = &quot;pred_weekend&quot;) %&gt;% 
  add_predictions(fit_week, var = &quot;pred_week&quot;) %&gt;%
  # Adjust for 0 values
  mutate(time = as.POSIXct(x, origin = min(tmp$time)),
         afternoon = x &gt; 43200,
         pred_commuting = ifelse(pred_commuting &lt; 0, 0, pred_commuting),
         pred_weekend = ifelse(pred_weekend &lt; 0, 0, pred_weekend),
         pred_week = ifelse(pred_week &lt; 0, 0, pred_week)) </code></pre>
<p><img src="/post/2018-11-03-munich-bike-data-info-graphic_files/figure-html/commuting_model_plot-1.png" width="960" style="display: block; margin: auto;" /></p>
<p>When we use this modeling approach, the predicted commuting traffic would look like this:</p>
<p><img src="/post/2018-11-03-munich-bike-data-info-graphic_files/figure-html/commuting_week_and_weekend_plot-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>The result looks quiet good. We are able to see the two peaks, one in the morning and another one in the afternoon.</p>
<h3 id="peak-commuting-times-according-to-model">Peak Commuting Times According to Model</h3>
<p>Now, that we have a model for commuting traffic, when are the peak times?</p>
<pre class="r"><code>morning &lt;- bike_cnt_15_min_modeled %&gt;% filter(!afternoon)
afternoon &lt;- bike_cnt_15_min_modeled %&gt;% filter(afternoon)
# Morning Peak
morning_peak &lt;- lubridate::with_tz(morning[which.max(morning$pred_commuting), ]$time, &quot;UTC&quot;)
cat(paste0(&quot;Morning peak:\n&quot;, format(morning_peak, &quot;%H:%M:%S&quot;)))</code></pre>
<pre><code>## Morning peak:
## 08:03:27</code></pre>
<pre class="r"><code># Afternoon Peak
afternoon_peak &lt;- lubridate::with_tz(afternoon[which.max(afternoon$pred_commuting), ]$time, &quot;UTC&quot;)
cat(paste0(&quot;Afternoon peak:\n&quot;, format(afternoon_peak, &quot;%H:%M:%S&quot;)))</code></pre>
<pre><code>## Afternoon peak:
## 17:54:48</code></pre>
<pre class="r"><code>time_diff &lt;- difftime(afternoon_peak,
                      morning_peak, units = &quot;hours&quot;, tz = &quot;UTC&quot;)

hours &lt;- floor((time_diff))
mins &lt;- floor(as.numeric(time_diff - hours, units = &quot;mins&quot;))
secs &lt;- as.numeric(time_diff - hours, units = &quot;secs&quot;) - mins * 60

peak_to_peak_duration &lt;- paste0(hours, &quot;h &quot;, mins, &quot;min &quot;, round(secs), &quot;sec&quot;)
cat(paste0(&quot;Peak to peak duration:\n&quot;, peak_to_peak_duration))</code></pre>
<pre><code>## Peak to peak duration:
## 9h 51min 21sec</code></pre>
<p>The morning peak is around 08:03:27 and the afternoon commuting peak is around 17:54:48. The peak to peak duration is 9h 51min 21sec.</p>
<p>Let’s go on and compare the two peak times a little bit further. When I was looking for a way to characterize the duration of a peak, I found a metric called <a href="https://en.wikipedia.org/wiki/Full_width_at_half_maximum">Full Duration Half Maximum (FDHM)</a>. It measures the duration between the points of y axis that are half the maximum amplitude.</p>
<p>We use this method for our data to get a FDHM for both peaks</p>
<pre class="r"><code>calculate_FDHM_stats &lt;- function(y, time, period_start, period_end) {
  period_filter &lt;-  time &gt;= period_start &amp; time &lt;= period_end
  y &lt;- subset(y, period_filter)
  time &lt;- subset(time, period_filter)
  max_y &lt;- max(y)
  
  # Calculate index of intersection points of max_y/2 and y within period
  i &lt;- c(FALSE, diff(max_y/2 &gt; y) != 0)
  times &lt;- time[i]
  y_vals &lt;- y[i]
  
  list(
    times = times,
    y_vals = y_vals,
    max_y = max_y,
    max_y_x_val = time[which.max(y)],
    fdhm = round(difftime(times[2], times[1], units = &quot;mins&quot;))
  )
}

day_start &lt;- as.POSIXct(&quot;1970-01-01 00:00:00&quot;)
noon &lt;- as.POSIXct(&quot;1970-01-01 12:00:00&quot;)
day_end &lt;- as.POSIXct(&quot;1970-01-01 23:59:59&quot;)

fdhm_stats_morning &lt;- calculate_FDHM_stats(bike_cnt_15_min_modeled$pred_commuting,
                     bike_cnt_15_min_modeled$time,
                     day_start,
                     noon)
fdhm_stats_afternoon &lt;- calculate_FDHM_stats(bike_cnt_15_min_modeled$pred_commuting,
                     bike_cnt_15_min_modeled$time,
                     noon,
                     day_end)

cat(paste0(&quot;Morning FDHM: \n&quot;, fdhm_stats_morning$fdhm, &quot; Minutes\n&quot;))</code></pre>
<pre><code>## Morning FDHM: 
## 140 Minutes</code></pre>
<pre class="r"><code>cat(paste0(&quot;Afternoon FDHM: \n&quot;, fdhm_stats_afternoon$fdhm, &quot; Minutes\n&quot;))</code></pre>
<pre><code>## Afternoon FDHM: 
## 197 Minutes</code></pre>
<pre class="r"><code>cat(paste0(&quot;Afternoon FDHM is &quot;, fdhm_stats_afternoon$fdhm - fdhm_stats_morning$fdhm,
           &quot; Minutes longer&quot;))</code></pre>
<pre><code>## Afternoon FDHM is 57 Minutes longer</code></pre>
<p>We create a plot to give a better visual understanding of these metrics:</p>
<pre class="r"><code>bike_cnt_15_min_modeled %&gt;% 
  ggplot() +
  geom_line(aes(x = time, y = pred_commuting), color = plot_colors[2]) +
  annotate(geom = &quot;ribbon&quot;, x = fdhm_stats_morning$times, ymax = Inf, ymin = -Inf, alpha = 0.1,
           fill = plot_colors[2]) +
  annotate(geom = &quot;ribbon&quot;, x = fdhm_stats_afternoon$times, ymax = Inf, ymin = -Inf, alpha = 0.1,
           fill = plot_colors[2]) +
  annotate(geom = &quot;text&quot;, 
           x = fdhm_stats_morning$times[1] - 2*60*60, 
           y = max(bike_cnt_15_min_modeled$pred_commuting),
           label = paste0(&quot;Morning FDHM:\n&quot;, fdhm_stats_morning$fdhm, &quot; Minutes&quot;),
           hjust = 0.5,
           vjust = 1,
           size = 3) +
  annotate(geom = &quot;text&quot;, 
           x = fdhm_stats_afternoon$times[2] + 2*60*60, 
           y = max(bike_cnt_15_min_modeled$pred_commuting),
           label = paste0(&quot;Afternoon FDHM:\n&quot;, fdhm_stats_afternoon$fdhm, &quot; Minutes&quot;),
           hjust = 0.5,
           vjust = 1,
           size = 3) +
  scale_x_datetime(labels = scales::date_format(&quot;%H:%M&quot;), date_breaks = &quot;2 hours&quot;) +
  xlab(&quot;Time of the Day&quot;) +
  ylab(&quot;Bikes per 15 Minutes&quot;) +
  ggtitle(&quot;According to the FDHM* metric the afternoon commuting peak lasts longer than the morning peak&quot;,
          &quot;*Full Duration Half Maximum: Duration between points of y axis that are half the maximum amplitude&quot;) +
  my_theme</code></pre>
<p><img src="/post/2018-11-03-munich-bike-data-info-graphic_files/figure-html/fdhm_plot-1.png" width="864" style="display: block; margin: auto;" /></p>
<p>As a last part of the peak analysis we compare the total bike counts within the modeled peaks to see whether those are comparable:</p>
<pre class="r"><code> bike_cnt_15_min %&gt;% 
  mutate(weekend = factor(ifelse(weekend == TRUE, &quot;Weekend&quot;, &quot;Week&quot;))) %&gt;% 
  group_by(weekend, time) %&gt;% 
  summarise(median = median(gesamt),
            q1 = quantile(gesamt, 0.25),
            q3 = quantile(gesamt, 0.75))  %&gt;% 
  mutate(peak = ifelse(time &lt; noon, 
                       &quot;morning&quot;,
                       &quot;afternoon&quot;)) %&gt;%  
  filter(weekend == &quot;Week&quot;) %&gt;% 
  group_by(peak) %&gt;% 
  summarise(bike_count = sum(median))  %&gt;% knitr::kable(digits = 2)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">peak</th>
<th align="right">bike_count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">afternoon</td>
<td align="right">612</td>
</tr>
<tr class="even">
<td align="left">morning</td>
<td align="right">302</td>
</tr>
</tbody>
</table>
<p>We see that the counts in the afternoon are twice as high as the morning counts. If people only would drive to work in the morning and back home in the afternoon, one would expect these two values to be equal. However, one explanation for this inequality could be that, once people finished their work, they don’t drive home immediately but go for other activities. These activities could be sports, meeting friends or doing the grocery, for instance. Thus, they would perhaps pass the counting stations more than once or pass a counting station which normally doesn’t lie on their commuting route. This could lead to the higher counts in the afternoon and would also be a explanation for some counts occurring very late in the evening (past 10pm).</p>
<h3 id="share-of-modeled-commuting-traffic">Share of Modeled Commuting Traffic</h3>
<p>Finally, we use our model to compute the share of commuting traffic during the week. To do so, we calculate the difference of daily counts between weekdays and weekend as well as the share of this difference on weekday counts.</p>
<pre class="r"><code>commuting_share &lt;- bike_cnt_day %&gt;% 
  mutate(weekend = ifelse(weekend == TRUE, &quot;weekend&quot;, &quot;week&quot;)) %&gt;% 
  spread(key = direction, value = count) %&gt;% 
  group_by(zaehlstelle, weekend) %&gt;% 
  summarise(median_count = median(gesamt)) %&gt;% 
  ungroup() %&gt;% 
  spread(key = weekend, value = median_count) %&gt;% 
  mutate(diff_week_weekend = week - weekend,
         share_commuting = diff_week_weekend / week) %&gt;% 
  arrange(zaehlstelle, desc(share_commuting)) %&gt;% 
  mutate(mean_share_commuting = mean(share_commuting),
         median_share_commuting = median(share_commuting))

commuting_share %&gt;% 
  select(zaehlstelle, share_commuting, mean_share_commuting, median_share_commuting) %&gt;% 
  knitr::kable(digits = 2)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">zaehlstelle</th>
<th align="right">share_commuting</th>
<th align="right">mean_share_commuting</th>
<th align="right">median_share_commuting</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Arnulf</td>
<td align="right">0.47</td>
<td align="right">0.42</td>
<td align="right">0.44</td>
</tr>
<tr class="even">
<td align="left">Erhardt</td>
<td align="right">0.39</td>
<td align="right">0.42</td>
<td align="right">0.44</td>
</tr>
<tr class="odd">
<td align="left">Hirsch</td>
<td align="right">0.51</td>
<td align="right">0.42</td>
<td align="right">0.44</td>
</tr>
<tr class="even">
<td align="left">Kreuther</td>
<td align="right">0.44</td>
<td align="right">0.42</td>
<td align="right">0.44</td>
</tr>
<tr class="odd">
<td align="left">Margareten</td>
<td align="right">0.43</td>
<td align="right">0.42</td>
<td align="right">0.44</td>
</tr>
<tr class="even">
<td align="left">Olympia</td>
<td align="right">0.29</td>
<td align="right">0.42</td>
<td align="right">0.44</td>
</tr>
</tbody>
</table>
<p>The modeled share of commuting traffic varies between the station and ranges from 29% to 51 %. The mean commuting share across all stations lies around 42%.</p>
<h1 id="summary">Summary</h1>
<p>Phew, that was a really long one! Thanks you for your interest in the analysis behind the info-graphic. I hope you got some interesting insights into the Munich bike traffic and found it as exciting as I did.</p>
<p>Let’s quickly sum up our analysis:</p>
<ul>
<li>To get a first overview, we created a map with all the stations.</li>
<li>We created a summary across all stations and for each station separately where we looked at the average 15 minute and daily counts, for instance. Further, we found out that Erhardt is the most frequented station and Kreuther has the fewest bike counts.</li>
<li>We found out that 5.8% of daily counted bikes at Arnulf Street arise from people driving at the wrong side of the road</li>
<li>We had a closer look on bike count records and found out about events like Münchner Ringparade and the 24h Mountain Bike Race in Munich.</li>
<li>Additionally we tried to figure out when most people are biking and how these days look like.</li>
<li>Finally we modeled the commuting traffic. Even if our commuting model is by far not perfect, it gave us some interesting insights on peak commuting times.</li>
</ul>
<p>Before I finish, I want to thank the Munich Open Data Team - especially Frank Börger and his coworker Lukas Raffl - for their great support and for providing me with inspirations and additional data. Also, great thanks to my friends and colleagues Ryan, Stephie, Flo and my girlfriend Samira for proof reading!</p>
<p>It’s getting winter now as I am writing this post, but I hope that your new knowledge about bike counts in Munich motivates you to also go out and ride your bike. Maybe you are living in Munich and want to add a few counts to the stations. If not, perhaps your city also has similar counting stations which you can check out. Try to do some research!</p>
<p>As always: If you want to add something or give me feedback just send me a message. I highly appreciate it! Also feel free to share the info-graphic with your friends, but please make sure to link the post in the resources!</p>
<h1 id="literature">Literature</h1>
<p><em>Zorn, Elisabeth; Hager, Gerhard; Wöppel, Hans-Dieter: Datenerhebungen zum Radverkehr in München Jg.55, Nr.1, 2011 (p.32 - 39)</em></p>
</div>
<hr />
<center>
<button class="btn btn-primary btn-outline" id="btn-toggle-analysis" onclick="showAnalysis()">
Show Analysis
</button>
</center>
<hr />
<script> 
function showAnalysis() {
    var btn = document.getElementById('btn-toggle-analysis');
    var x = document.getElementById('analysis');
        if (x.style.display === 'none') {
            btn.firstChild.data = "Hide Analysis";
            x.style.display = 'block';
        } else {
            btn.firstChild.data = "Show Analysis"
            x.style.display = 'none';
    }
}
</script>

    </div>

    


<div class="article-tags">
  
  <a class="btn btn-primary btn-outline" href="/tags/munich-open-data">Munich Open Data</a>
  
  <a class="btn btn-primary btn-outline" href="/tags/r">R</a>
  
  <a class="btn btn-primary btn-outline" href="/tags/bike-data">Bike Data</a>
  
</div>




    
    
    <div class="article-widget">
      <div class="hr-light"></div>
      <h3>Related</h3>
      <ul>
        
        <li><a href="/post/oktoberfest-analysis-part-ii/">Oktoberfest Analysis Part II</a></li>
        
        <li><a href="/post/oktoberfest-analysis-part-i/">Oktoberfest Analysis Part I</a></li>
        
        <li><a href="/post/usa-school-shootings/">USA School Shootings</a></li>
        
        <li><a href="/post/san-francisco-crime-heatmaps-in-r-using-bigquery-bigrquery-and-ggmap/">San Francisco Crime Heatmaps in R Using BigQuery bigrquery and ggmap</a></li>
        
      </ul>
    </div>
    

    
    <div class="article-widget">
      <div class="post-nav">
  
  <div class="post-nav-item">
    <div class="meta-nav">Next</div>
    <a href="/post/using-dynamically-rendered-r-markdown-childs-for-reports/" rel="next">Dynamically Rendered Flexdashboard Pages Using RMarkdown Childs</a>
  </div>
  
  
  <div class="post-nav-item">
    <div class="meta-nav">Previous</div>
    <a href="/post/usa-school-shootings/" rel="prev">USA School Shootings</a>
  </div>
  
</div>

    </div>
    

    


  </div>
</article>

<footer class="site-footer">
  <div class="container">
    <p>
      <a href="privacy-note.html">Privacy Note</a>
    </p>
  </div>
  <hr />
  
  <div class="container">
    <p class="powered-by">

      &copy; 2018 &middot; 

      Powered by the
      <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
      <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

      <span class="pull-right" aria-hidden="true">
        <a href="#" id="back_to_top">
          <span class="button_icon">
            <i class="fa fa-chevron-up fa-2x"></i>
          </span>
        </a>
      </span>

    </p>
  </div>
</footer>


<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close btn-large" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Cite</h4>
      </div>
      <div>
        <pre><code class="modal-body tex"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-primary btn-outline js-copy-cite" href="#" target="_blank">
          <i class="fa fa-copy"></i> Copy
        </a>
        <a class="btn btn-primary btn-outline js-download-cite" href="#" target="_blank">
          <i class="fa fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

    

    
    

    

    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" integrity="sha512-3P8rXCuGJdNZOnUx/03c1jOTnMn3rP63nBip5gOP2qmUh5YAdVAvFZ1E+QLZZbC1rtMrQb+mah3AfYW11RUrWA==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.3/imagesloaded.pkgd.min.js" integrity="sha512-umsR78NN0D23AzgoZ11K7raBD+R6hqKojyBZs1w8WvYlsI+QuKRGBx3LFCwhatzBunCjDuJpDHwxD13sLMbpRA==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha512-iztkobsvnjKfAtTNdHkGVjAYTrrtlC7mGp/54c40wowO7LhURYl3gVzzcEqGl/qKXQltJ2HwMrdLcNUdo+N/RQ==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.4/isotope.pkgd.min.js" integrity="sha512-VDBOIlDbuC4VWxGJNmuFRQ0Li0SKkDpmGyuhAG5LTDLd/dJ/S0WMVxriR2Y+CyPL5gzjpN4f/6iqWVBJlht0tQ==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js" integrity="sha256-X5PoE3KU5l+JcX+w09p/wHl9AzK333C4hJ2I9S5mD4M=" crossorigin="anonymous"></script>
    
    
    <script src="/js/hugo-academic.js"></script>
    

    
    
      
      
      <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js" integrity="sha256-/BfiIkHlHoVihZdc6TFuj7MmJ0TWcWsMXkeDFwhi0zw=" crossorigin="anonymous"></script>
      

      

      

      <script>hljs.initHighlightingOnLoad();</script>
    

    
    

  </body>
</html>

